### ISSUE TITLE
parsing text paragraphs

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/tinkr#12]
I've discovered an additional usage for this package - the existence of journals that accept submissions in their own wacky XML format, yet not markdown. Strange but true. `tinkr` is the (almost) perfect solution - thanks @jeroen!

Running `to_xml()` on one of these breaks every line at around 70 characters, resulting in
```
<paragraph>
    <text xml:space="preserve">
        A first bit of text that will ultimately only go on until it reaches a break
    </text>
    <softbreak/>
    <text xml:space="preserve">
        Oh there it was when i was least expecting it and it's kinda annoying
    </text>
</paragraph>
```
Obviously the desired result would just be `<paragraph>bunch of text</paragraph>`. Any idea whence these `<softbreak/>` interjections? Easy to remove after the fact, but kinda pesky, so help appreciated! Oh, and they do not reflect any kind of existing `<softbreak/>`s in the actual text which has been hard-joined into single-line paragraphs.

**Comment by maelle** [comment]
:wave:! Cool use case and weird! I can only have a quick look now and am wondering whether the issue is with `commonmark` itself?

**Comment by mpadge** [comment]
Oh yeah, sorry @maelle, didn't actually check the DESCR to see that you are the almighty creator here, not Jeroen. Please redirect an equal portion of that gratitude to yourself. There's no rush at all with this, and you may also feel free just to close it, but it's definitely a quirky issue for whenever you or @jeroen might have time.

**Comment by mpadge** [comment]
Oh no, actually it's `rmarkdown::render()` itself. I was using that to `render("doc.Rmd", md_document())` as a first step, and that inserts all of the `<softbreak/>` junk. It is also completely unnecessary, and `commonmark::markdown_xml("doc.Rmd")` does a perfect job, and so therefore does `tinkr::to_xml()`. All good, thanks!

**Comment by maelle** [comment]
Awesome!
