### ISSUE TITLE
to_md() removes empty rows from tables

### ISSUE THREAD

**Issue by zkamvar** [ropenscilabs/tinkr#21]
I'm also getting an xslt error: `Unsupported element 'table_row'`

``` r
f <- tempfile()
ff <- tempfile()
x <- "
| A column | Another column | A third column |   |   |
|----------|----------------|----------------|---|---|
| a        | a              | a              |   |   |
| a        | a              | a              |   |   |
|          |                |                |   |   |
| a        | a              | a              |   |   |
|          |                |                |   |   |
"
writeLines(x, f)
tinkr::to_md(tinkr::to_xml(f), ff)
readLines(ff)
#> [1] "| A column | Another column | A third column |  |  | "
#> [2] "| -------- | -------------- | -------------- |  |  |" 
#> [3] "| a        | a              | a              |  |  | "
#> [4] "| a        | a              | a              |  |  | "
#> [5] "| a        | a              | a              |  |  | "
#> [6] ""                                                     
#> [7] ""
```

<sup>Created on 2020-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

_Originally posted by @zkamvar in https://github.com/ropenscilabs/tinkr/pull/17#discussion_r492810960_

**Comment by maelle** [comment]
Can you please try my latest commit?

**Comment by zkamvar** [comment]
> Can you please try my latest commit?

I saw it just after I had created #22 and I think we ended up with the same idea! I did find that the tables were weird if the contents inside the tables were of different lengths (see example in #22), but I was able to fix that. It happily even fixes cells with added information :)

**Comment by pdaengeli** [comment]
I think removing the predicate `[.//md:text]"` as suggested in https://github.com/zkamvar/tinkr/commit/1658e5f0b36415771cf36b0d096b11fbf701d21d#diff-8235a27dde7b8c2195545fb445ec0226L142-R142 is cleaner than the duplication of the template applied in https://github.com/ropenscilabs/tinkr/commit/4980e816d876a86bb1ea07fe2b564701bc4bce22#diff-8235a27dde7b8c2195545fb445ec0226R148-R151.
