### ISSUE TITLE
tables are not preserved

### ISSUE THREAD

**Issue by ginolhac** [ropenscilabs/tinkr#4]
Thanks for a nice package,

it seems that tables are stripped out such as

```
## tables


--------------------
a    b    c
--- ---  -----------
1    2    3

--------------------
```

is transformed in 

```
## tables

***

a    b    c

***

1    2    3

***
```

using `to_md(to_xml("tinkr.Rmd"), "tinkr2.Rmd")`

**Comment by maelle** [comment]
Thank you! Linked to #2 -- I need to learn enough XSL to improve the stylesheet. Once I do, in the first step I can use the `commonmark` `extensions=TRUE` argument, this way tables would be tables in the XML, and then they'd get written back to the Markdown file whereas currently I let them as text which means they're not protected. 😢 

Thanks again for testing the package!

**Comment by maelle** [comment]
@ginolhac now tables are supported... but the alignment of columns is lost in the process. So I'll leave this issue open for now, but if you have no alignment information for columns in your (R)Markdown, please test this.

Related to https://github.com/jeroen/commonmark/issues/9

**Comment by maelle** [comment]
@ginolhac can you try again, after installing `commonmark` latest version from GitHub? Now table alignemtn isn't lost (what's lost is the prettiness of headers, they'll have three dashes instead of a length corresponding to the longest string in the column).

**Comment by maelle** [comment]
Oops sorry it still doesn't work, because there aren't "|" between cells. Can you remind me how you created these tables? Is this output from something in R?

**Comment by maelle** [comment]
Actually your table isn't a real table, so it seems we'll have trouble supporting this, but I'm glad to help if it's output from R! We might be able to find a way to protect such text. 🤔

**Comment by ginolhac** [comment]
I am creating them by hand, since it is my labbook, it is easy to add new items.

based on https://www.markdownguide.org/extended-syntax/ the pipes are optional, and so far their absence was fine. But if it is too much of hassle for you, I am fine closing the issue. `grep` is doing the job even if it is not elegant

**Comment by maelle** [comment]
@jeroen `commonmark` doesn't recognized tables without "|", does it?

**Comment by maelle** [comment]
Test of GitHub rendering

## tables


--------------------
a    b    c
--- ---  -----------
1    2    3

--------------------

**Comment by ginolhac** [comment]
closing as this was very specific and now I have a different set-up more cleaner with data in tsv and formatting in my own package. Thanks again for the help
